---
/**:
  ros__parameters:
    device: cuda:0
    visualization.publish_markers: false
    verbose_info_logs: true

    pose_estimator_type: cosypose
    cosypose:
      dataset_name: ycbv
      renderer:
        renderer_type: panda3d
        n_workers: 8
        gpu_renderer: false
      inference:
        detector:
          detection_th: 0.7
        pose_estimator:
          n_coarse_iterations: 1
          n_refiner_iterations: 3
        labels_to_keep:
        - ycbv-obj_000002
        - ycbv-obj_000005
    camera_names: [cam_1]
    cameras:
      timeout: 0.1
      n_min_cameras: 1
      cam_1:
        leading: true
        publish_tf: false
        compressed: false
