---
/**:
  ros__parameters:
    # Timing and frames configuration
    # compensate_camera_motion: true
    # camera_motion_stationary_frame_id: world
    detection_to_image_time_slop: 10.0
    # Tracker configuration
    optimizer.tikhonov_parameter_rotation: 20000.0
    optimizer.tikhonov_parameter_translation: 500000.0

    region_modality.model_occlusion: true
    region_modality.learning_rate_f: 0.5
    region_modality.learning_rate_b: 0.5

    use_texture_modality: true
    use_depth: true
    # Tracked objects configuration
    tracked_objects:
    - ycbv-obj_000001
    - ycbv-obj_000002
    - ycbv-obj_000003
    - ycbv-obj_000004
    - ycbv-obj_000005
    - ycbv-obj_000006
    - ycbv-obj_000007
    - ycbv-obj_000008
    - ycbv-obj_000009
    - ycbv-obj_000010
    - ycbv-obj_000011
    - ycbv-obj_000012
    - ycbv-obj_000013
    - ycbv-obj_000014
    - ycbv-obj_000015
    - ycbv-obj_000016
    - ycbv-obj_000017
    - ycbv-obj_000018
    - ycbv-obj_000019
    # - ycbv-obj_000020
    # - ycbv-obj_000021
    # - ycbv-obj_000022
    # - ycbv-obj_000023
    # - ycbv-obj_000024
    # - ycbv-obj_000025
    # - ycbv-obj_000026
    # - ycbv-obj_000027
    # - ycbv-obj_000028
    # - ycbv-obj_000029
    # - ycbv-obj_000030

    # ycbv-obj_000026.max_instances: 2
    # ycbv-obj_000001.max_instances: 5
    # ycbv-obj_000021.max_instances: 5
    # ycbv-obj_000023.max_instances: 5
